apiVersion: extensions/v1beta1
kind: DaemonSet
metadata: 
  name: sim-os-agent
spec: 
  template: 
    metadata: 
      labels: 
        name: sim-os-agent
    spec:
      serviceAccountName: appd-sim-agent
      containers:
      - env:
        - name: IS_K8_DEPLOYMENT
          value: "true"
        - name: ACCOUNT_ACCESS_KEY
          value: <change-me>
        - name: ACCOUNT_NAME
          value: customer1
        - name: APPLICATION_NAME
          value: <change-me>
        - name: APPLICATION_NAME_FROM
          value: <change-me>
        - name: APPLICATION_NAME_FROM_VALUE
          value: <change-me>
        - name: CONTROLLER_HOST
          value: <change-me>
        - name: CONTROLLER_PORT
          value: "8090"
        - name: CONTROLLER_SSL_ENABLED
          value: "false"
        - name: EVENT_SERVICE_URL
          value: <change-me>:9080
        - name: GLOBAL_ACCOUNT_NAME
          value: <change-me>
        - name: TIER_NAME_FROM
          value: CONTAINER_NAME
        - name: TIER_NAME_FROM_VALUE
          value: tier-name
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: METRIC_LIMIT
          value: "2000"
        image: jdbarfield/dynamic-agent-k8:1.1.14
        securityContext:
          privileged: true
        name: sim-os-agent
        resources: {}
        volumeMounts:
        - mountPath: /hostroot
          name: hostroot
          readOnly: true
        - mountPath: /var/run/docker.sock
          name: docker-sock
      restartPolicy: Always
      volumes:
      - name: hostroot
        hostPath:
          path: /
          type: Directory
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
          type: Socket

---
apiVersion: v1
kind: Service
metadata:
  name: machine-agent
spec:
  selector:
    name: sim-os-agent
  ports:
  - name: "9090"
    port: 9090
    targetPort: 9090
status:
  loadBalancer: {}